apiVersion: v1
kind: ConfigMap
metadata:
  name: frappe-config
  namespace: frappe
data:
  SITE_NAME: "siud.local"
  DB_HOST: "mariadb"
  DB_PORT: "3306"
  REDIS_CACHE: "redis://redis-cache:6379"
  REDIS_QUEUE: "redis://redis-queue:6379"
