apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe-scheduler
  namespace: frappe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe-scheduler
  template:
    metadata:
      labels:
        app: frappe-scheduler
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: scheduler
          image: artifactory.snifim.blroot/remote_registry_docker_io/frappe/erpnext:v16
          securityContext:
            allowPrivilegeEscalation: false
          command: ["bench", "schedule"]
          envFrom:
            - configMapRef:
                name: frappe-config
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: frappe-sites
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe-worker-short
  namespace: frappe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe-worker-short
  template:
    metadata:
      labels:
        app: frappe-worker-short
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: worker
          image: artifactory.snifim.blroot/remote_registry_docker_io/frappe/erpnext:v16
          securityContext:
            allowPrivilegeEscalation: false
          command: ["bench", "worker", "--queue", "short"]
          envFrom:
            - configMapRef:
                name: frappe-config
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: frappe-sites
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frappe-worker-long
  namespace: frappe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frappe-worker-long
  template:
    metadata:
      labels:
        app: frappe-worker-long
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: worker
          image: artifactory.snifim.blroot/remote_registry_docker_io/frappe/erpnext:v16
          securityContext:
            allowPrivilegeEscalation: false
          command: ["bench", "worker", "--queue", "long"]
          envFrom:
            - configMapRef:
                name: frappe-config
          volumeMounts:
            - name: sites
              mountPath: /home/frappe/frappe-bench/sites
      volumes:
        - name: sites
          persistentVolumeClaim:
            claimName: frappe-sites
