apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frappe
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mariadb.yaml
  - redis.yaml
  - frappe-single-pod.yaml
  - portal-ui.yaml
  - ingress-tanzu.yaml
images:
  - name: frappe-siud
    newName: gcr.io/PROJECT/frappe-siud
    newTag: latest
  - name: portal-ui
    newName: gcr.io/PROJECT/portal-ui
    newTag: latest
