apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frappe
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mariadb.yaml
  - redis.yaml
  - frappe-single-pod.yaml
  - portal-ui.yaml
  - ingress-tanzu.yaml
patches:
  - path: security-patch.yaml
    target:
      kind: Deployment
  - path: security-patch-statefulset.yaml
    target:
      kind: StatefulSet
images:
  - name: frappe-siud
    newName: artifactory.snifim.blroot/remote_registry_docker_io/frappe-siud
    newTag: latest
  - name: portal-ui
    newName: artifactory.snifim.blroot/remote_registry_docker_io/portal-ui
    newTag: latest
